// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-todo-clean-app/rest/handler"
)

// Injectors from wire.go:

func InitSystemHandler() *handler.SystemHandler {
	systemHandler := handler.NewSystemHandler()
	return systemHandler
}
