// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-todo-clean-app/driver"
	"go-todo-clean-app/gateway"
	"go-todo-clean-app/rest/handler"
	"go-todo-clean-app/usecase"
)

// Injectors from wire.go:

func InitSystemHandler() *handler.SystemHandler {
	systemHandler := handler.NewSystemHandler()
	return systemHandler
}

func InitTodoHandler() *handler.TodoHandler {
	db := driver.ProvideDatabaseConnection()
	todoDriver := driver.ProvideTodoDriver(db)
	todoPort := gateway.ProvideTodoPort(todoDriver)
	todoUsecase := usecase.ProvideTodoUsecase(todoPort)
	todoHandler := handler.ProvideTodoHandler(todoUsecase)
	return todoHandler
}
